---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - learning.aca.com
  resources:
  - bluegreendeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - learning.aca.com
  resources:
  - bluegreendeployments/finalizers
  verbs:
  - update
- apiGroups:
  - learning.aca.com
  resources:
  - bluegreendeployments/status
  verbs:
  - get
  - patch
  - update
