apiVersion: learning.aca.com/v1alpha1
kind: BlueGreenDeployment
metadata:
  labels:
    app.kubernetes.io/name: bg-deployment-controller
    app.kubernetes.io/managed-by: kustomize
  name: bluegreendeployment-sample
  namespace: default
spec:
  deployment:
    replicas: 1
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
  service:
    selector:
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 9376
