apiVersion: learning.aca.com/v1alpha1
kind: BlueGreenDeployment
metadata:
  labels:
    app.kubernetes.io/name: bg-deployment-controller
    app.kubernetes.io/managed-by: kustomize
  name: app
  namespace: default
spec:
  deployment:
    replicas: 1
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.28.0-alpine
          ports:
          - containerPort: 80
  service:
    type: ClusterIP
    selector:
      app: nginx
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
  tests:
    - name: smoke
      http:
        path: /
        port: 80
        initialDelaySeconds: 180
        timeoutSeconds: 6

